<?php

namespace Database\Seeders;

use App\Models\Karyawan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 'USR001',
                'nippt' => '198802081755',
                'nama' => 'MARKOS, S.TP',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1997-06-20',
                'telepon' => '',
                'email' => 'markos@mail.com',
                'jabatan' => 'JASA PENGGERAK SWADAYA MASYARAKAT',
            ],
            [
                'id' => 'USR002',
                'nippt' => '199004111810',
                'nama' => 'PURNADI, S.Sos',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1996-06-15',
                'telepon' => '',
                'email' => 'purnadi@mail.com',
                'jabatan' => 'JASA PRANATA HUMAS',
            ],
            [
                'id' => 'USR003',
                'nippt' => '198802222351',
                'nama' => 'ANANG PUTRA RELA, SE',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1995-06-11',
                'telepon' => '',
                'email' => 'anang@mail.com',
                'jabatan' => 'JASA PRANATA HUMAS',
            ],
            [
                'id' => 'USR004',
                'nippt' => '199212242437',
                'nama' => 'DESTI WAHANA S.Sos',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1994-06-06',
                'telepon' => '',
                'email' => 'desti@maip.com',
                'jabatan' => 'JASA PRANATA KOMPUTER',
            ],
            [
                'id' => 'USR005',
                'nippt' => '199212232364',
                'nama' => 'DEVI FITRIA, S.Sos',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1993-06-01',
                'telepon' => '',
                'email' => 'devi@maip.com',
                'jabatan' => 'JASA ARSIPARIS',
            ],
            [
                'id' => 'USR006',
                'nippt' => '199204082365',
                'nama' => 'MARADONA, S.Pi',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1992-05-27',
                'telepon' => '',
                'email' => 'maradona@maip.com',
                'jabatan' => 'JASA ARSIPARIS',
            ],
            [
                'id' => 'USR007',
                'nippt' => '199109082394',
                'nama' => 'SY NORMALISA MULIA, S.Sos',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1991-05-23',
                'telepon' => '',
                'email' => 'sy@maip.com',
                'jabatan' => 'JASA PERENCANA',
            ],
            [
                'id' => 'USR008',
                'nippt' => '199209193645',
                'nama' => 'DAMRI S.IP',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1990-05-18',
                'telepon' => '',
                'email' => 'damri@mail.com',
                'jabatan' => 'JASA ANALIS SDM APARATUR',
            ],
            [
                'id' => 'USR009',
                'nippt' => '199711264609',
                'nama' => 'MERI KARTIKA, S.M',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1989-05-13',
                'telepon' => '',
                'email' => 'meri@maip.com',
                'jabatan' => 'JASA ANALIS SDM APARATUR',
            ],
            [
                'id' => 'USR010',
                'nippt' => '199701105774',
                'nama' => 'YULIA, S.Psi',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1988-05-08',
                'telepon' => '',
                'email' => 'yulia@maip.com',
                'jabatan' => 'JASA PRANATA KOMPUTER',
            ],
            [
                'id' => 'USR011',
                'nippt' => '198601170970',
                'nama' => 'DERY TRESIA',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1987-05-04',
                'telepon' => '',
                'email' => 'dery@mail.com',
                'jabatan' => 'JASA PENGADMINISTRASI PERKANTORAN',
            ],
            [
                'id' => 'USR012',
                'nippt' => '199707014947',
                'nama' => 'M. AL HAYYI RABBANI',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1986-04-29',
                'telepon' => '',
                'email' => 'm@mail.com',
                'jabatan' => 'JASA PENGADMINISTRASI PERKANTORAN',
            ],
            [
                'id' => 'USR013',
                'nippt' => '200002194949',
                'nama' => 'SOFIA ANDINI',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1985-04-24',
                'telepon' => '',
                'email' => 'sofia@maip.com',
                'jabatan' => 'JASA PENGADMINISTRASI PERKANTORAN',
            ],
            [
                'id' => 'USR014',
                'nippt' => '199003030048',
                'nama' => 'MUCIANA',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1984-04-19',
                'telepon' => '',
                'email' => 'muciana@mail.com',
                'jabatan' => 'JASA PENGELOLA DATA DAN INFORMASI',
            ],
            [
                'id' => 'USR015',
                'nippt' => '197704110328',
                'nama' => 'HARMAINI',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1983-04-15',
                'telepon' => '',
                'email' => 'harmaini@mail.com',
                'jabatan' => 'JASA PENGELOLA DATA DAN INFORMASI',
            ],
            [
                'id' => 'USR016',
                'nippt' => '197004010416',
                'nama' => 'ASRIN',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1982-04-10',
                'telepon' => '',
                'email' => 'asrin@mail.com',
                'jabatan' => 'JASA PENGADMINISTRASI PERKANTORAN',
            ],
            [
                'id' => 'USR017',
                'nippt' => '198608030417',
                'nama' => 'ANDRIANSYAH',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1981-04-05',
                'telepon' => '',
                'email' => 'andriansyah@mail.com',
                'jabatan' => 'JASA PENGADMINISTRASI PERKANTORAN',
            ],
            [
                'id' => 'USR018',
                'nippt' => '198808210969',
                'nama' => 'WIDIA ASTUTI',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1980-03-31',
                'telepon' => '',
                'email' => 'widia@maip.com',
                'jabatan' => 'JASA PENGELOLA KEPEGAWAIAN',
            ],
            [
                'id' => 'USR019',
                'nippt' => '198109181185',
                'nama' => 'ROZIAH',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1979-03-27',
                'telepon' => '',
                'email' => 'roziah@maip.com',
                'jabatan' => 'JASA PENGADMINISTRASI PERKANTORAN',
            ],
            [
                'id' => 'USR020',
                'nippt' => '196812244907',
                'nama' => 'SAPEI SAFRI',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1978-03-22',
                'telepon' => '',
                'email' => 'sapei@mail.com',
                'jabatan' => 'JASA PRAMU KEBERSIHAN',
            ],
            [
                'id' => 'USR021',
                'nippt' => '199211084787',
                'nama' => 'APRIANTO',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1977-03-17',
                'telepon' => '',
                'email' => 'aprianto@mail.com',
                'jabatan' => 'JASA PRAMU KEBERSIHAN',
            ],
            [
                'id' => 'USR022',
                'nippt' => '198707184869',
                'nama' => 'SAMSUL FATONI',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => '',
                'tanggal_lahir' => '1976-03-12',
                'telepon' => '',
                'email' => 'samsul@mail.com',
                'jabatan' => 'JASA PRAMU KEBERSIHAN',
            ],
        ];

        Karyawan::insert($data);
    }
}
